# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [ ]:
!pip install numpy
## "!"" permite correr comandos del sistema directamente desde una celda de Jupyter.


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 4.8 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.6 MB 5.3 MB/s eta 0:00:02
   --------- ------------------------------ 3.1/12.6 MB 5.6 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 5.7 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 5.6 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.6 MB 5.3 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 5.1 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.6 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 4.8 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   -


[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


**Importaciones:**

In [3]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo: 
# uso arange de NumPy que genera numeros enteros consecutivos
array_numeros = np.arange(10)

# mostrar
print(array_numeros)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [9]:
#todo:
array_ceros = np.zeros(5, dtype=int) #dtype=int asegura que los valores sean enteros
print(array_ceros)

# modificar el array
array_ceros[2] = 5

print(array_ceros)



[0 0 0 0 0]
[0 0 5 0 0]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [11]:
#todo: 
# función random.rand para generar la matriz entre 0 y 1
matriz_aleatoria = np.random.rand(3,3) 

# mostramos la matriz
print(matriz_aleatoria)

[[0.17043161 0.26266863 0.17316951]
 [0.26554592 0.48573985 0.98899247]
 [0.51948146 0.45932852 0.91447194]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:

arr = np.array([10, 20, 30, 40, 50])
print(f"array original: {arr}")

# sumamos 5 a cada elemento del array original
arr_sumado = arr + 5
print(f"array sumado: {arr_sumado}")

# creamos un numero aleatorio con randint
numero_aleatorio = randint(1, 10)
print(f"numero aleatorio: {numero_aleatorio}")

# multiplicamos cada elemento del array original por el numero aleatorio
arr_multiplicado = arr * numero_aleatorio
print(f"array multiplicado: {arr_multiplicado}")

# multiplicamos el array sumado por el numero aleatorio
array_final = arr_sumado * numero_aleatorio
print(f"array final: {array_final}")



array original: [10 20 30 40 50]
array sumado: [15 25 35 45 55]
numero aleatorio: 2
array multiplicado: [ 20  40  60  80 100]
array final: [ 30  50  70  90 110]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [25]:
#todo:

# uso la funcion identity de Numpy
matriz_identidad = np.identity(4)

print(matriz_identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [29]:
#todo: 

# arange para los numeros pares
array_pares = np.arange(0, 21, 2)

print(f"array de numeros pares: {array_pares}")

# definir un numero para hacer las operaciones, en este caso 4
numero_operacion = 4
print(f"numero para las operaciones: {numero_operacion}")

# hacer las operaciones
suma = array_pares + numero_operacion
resta = array_pares - numero_operacion
multiplicacion = array_pares * numero_operacion
division = array_pares / numero_operacion

# mstrar los resultados
print("suma:", suma)
print("resta:", resta)
print("multiplicación:", multiplicacion)
print("división:", division)


array de numeros pares: [ 0  2  4  6  8 10 12 14 16 18 20]
numero para las operaciones: 4
suma: [ 4  6  8 10 12 14 16 18 20 22 24]
resta: [-4 -2  0  2  4  6  8 10 12 14 16]
multiplicación: [ 0  8 16 24 32 40 48 56 64 72 80]
división: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
